export const messages: Record<string, string[]> = {
  midnight: [
    "Past midnight. Everyone's asleep, but you're awake with fear staring you down. Prove you're tougher.",
    "Dark hours. The weak sleep while you're forced to face the silence that judges you.",
    "Silence at night grips you tight, either your strength or your doom.",
    "The world sleeps while you fight to build or rot in your own dread.",
    "It's late. Only the bold or the hunted survive these cruel hours.",
    "Every second past midnight rips from tomorrow, make it count or crumble.",
    "Past midnight. Comfort is for the weak, and you're not weak enough to quit.",
    "They dream while you grind, or you'll lose everything you chase.",
    "Midnight isn't for rest, it's a brutal test of your will to live.",
    "While others recharge, you battle on or get buried by the dark.",
  ],
  night: [
    "Dead of night. No hiding, the quiet presses in to break you.",
    "Darkness reveals your limits, fail and it will crush you.",
    "No noise, no escape, just your will against the endless night.",
    "These hours shatter the fragile, stand strong or fall apart.",
    "The shadows demand you keep moving or they swallow you whole.",
    "Dead of night. You sharpen yourself or rust away in fear.",
    "Loneliness weighs heavy, prove you're not weak under it.",
    "The night punishes the lazy with every passing minute.",
    "Everyone's gone, and your excuses vanish with them.",
    "Silence crushes you, handle it or be destroyed.",
  ],
  preDawn: [
    "Pre-dawn. They snore while you push or get left in the dust.",
    "Before sunrise, the day belongs to those who fight hardest.",
    "Pre-dawn hours weed out the quitters, keep going or lose.",
    "Wakefulness now gives you power they can't touch.",
    "Every minute before dawn is a weapon, use it or fail.",
    "While they rest, you rise or get forgotten.",
    "Pre-dawn proves you're ahead, slack off and you're nothing.",
    "This hour belongs to the ruthless, claim it or crawl.",
    "The sky's dark, but your drive must burn or fade.",
    "Beat the sun or let everyone overtake you.",
  ],
  earlyMorning: [
    "Early morning. You're already behind, hustle or watch it slip away.",
    "Sleep longer and you lose ground fast, pick a side.",
    "The day started without you, catch up or fall flat.",
    "Every wasted minute now drags you down harder later.",
    "Early morning is your chance to move, don't stumble.",
    "If you're slow now, the day will grind you into nothing.",
    "Sunrise waits for no one, neither should you.",
    "You're either sharp now or useless all day long.",
    "Early hours demand you act, not yawn through them.",
    "They call it morning, you turn it into a battle to survive.",
  ],
  morning: [
    "Morning. Move fast or your mistakes will haunt you all day.",
    "The day's fresh, waste it and regret will eat you alive.",
    "Your speed now shapes how you end up later.",
    "Mornings are for action, not dragging your feet.",
    "Quick and steady wins, slow down and you're done.",
    "Start strong or the day will tear you apart.",
    "Morning focus beats evening shame every time.",
    "Don't stumble into your tasks, hit them hard.",
    "Momentum here is everything, lose it and you're lost.",
    "Every delay now echoes as failure tonight.",
  ],
  lateMorning: [
    "Late morning. Choose grit or laziness will ruin you.",
    "Half the day's gone, what's stopping you now?",
    "Late morning is a fight, push or you're finished.",
    "Stop stalling, time's slipping through your fingers.",
    "Your effort now decides if you make it tonight.",
    "Momentum or failure, decide before it's too late.",
    "Late morning isn't rest, it's a war you can't lose.",
    "Don't drift, the day's laughing at your weakness.",
    "Fight the slowdown or sink into nothing.",
    "This is your warning, late morning spares no one.",
  ],
  midday: [
    "Midday. Eat quick and act or you'll drown in it.",
    "The clock doesn't care, move or get buried.",
    "Midday is no break, it's your last sprint.",
    "This hour builds you up or breaks you down.",
    "Refuel fast, then hit harder or collapse.",
    "While they eat, you rule or get left behind.",
    "Don't rest, strike now or lose everything.",
    "Midday weakness is death, crush it fast.",
    "Lunch is for the weak, you're built for this.",
    "Midday heat tests you, fail and you're done.",
  ],
  earlyAfternoon: [
    "Early afternoon. Keep going even when you're shaking.",
    "This slump destroys the weak, don't be one.",
    "Discipline keeps you alive, slow down and die.",
    "The weak nap, you deliver or you're nothing.",
    "Early afternoon splits winners from losers, choose.",
    "Tired? Push or the day owns you.",
    "The fight's not over, stay in it or fall.",
    "Early afternoon exposes fakes, prove you're real.",
    "The clock taunts you, answer with work.",
    "Stay strong when others fade or get crushed.",
  ],
  lateAfternoon: [
    "Late afternoon. Keep pushing or the day will break you.",
    "The end's not near, don't give up now.",
    "Every hour hits harder, stay tough.",
    "Don't slack, the day punishes the weak.",
    "Push past the pain or the wall wins.",
    "Fatigue lies to you, fight through it.",
    "Late afternoon judges you, don't fail.",
    "This is where you build or shatter.",
    "Winners push harder, quitters fade out.",
    "Late afternoon demands grind until you drop.",
  ],
  evening: [
    "Evening. Fix your flaws or weakness will destroy you.",
    "Day's ending, but your standards stay high.",
    "Tie up every loose end or regret it.",
    "Don't leave gaps, they'll ruin you later.",
    "Evening is when you face your failures.",
    "Repair now or repeat your mistakes.",
    "The sun's gone, but your fight isn't.",
    "Evening sorts the real from the fake.",
    "What you skip now haunts you tomorrow.",
    "Evening is for strength, not softness.",
  ],
  lateEvening: [
    "Late evening. Face your mistakes and force more out.",
    "Don't slow down, finish with all you've got.",
    "Night closes in, prove you're tougher.",
    "Check, fix, and fight on.",
    "Late evening tests your grit, don't break.",
    "Push harder, sleep is a reward you earn.",
    "This is your hard truth hour, be brutal.",
    "Late evening demands no weakness.",
    "Finish strong or collapse into nothing.",
    "Keep battling, tomorrow waits for no one.",
  ],
  nightEnd: [
    "Night. Sleep is a gift you haven't earned, fight for it.",
    "The day's nearly dead, are you proud yet?",
    "Midnight looms, did you do enough?",
    "Sleep takes from the bold, don't give in.",
    "End the day with force, not whispers.",
    "Your bed pulls, but you're too weak to stop.",
    "Earn rest with sweat, not lazy dreams.",
    "Night hides your sloth, don't let it win.",
    "The clock hits hard, what did you hit?",
    "Sleep is a debt, pay with effort first.",
  ],
};
